alias doc="docker container"
alias doi="docker image"
alias dos="docker system"
alias dop="docker system prune --volumes"

alias dc="docker-compose"
alias dcu="docker-compose up --detach"
alias dcd="docker-compose down"
alias dcs="docker-compose stop"
alias dcb="docker-compose build"
alias dcr="docker-compose run --rm"
alias dce="docker-compose exec"
alias dcp="docker-compose ps -a"
alias dcl="docker-compose logs"

alias ddu="docker-compose -f docker-compose.dependencies.yml up --detach"
alias ddd="docker-compose -f docker-compose.dependencies.yml down"
alias dds="docker-compose -f docker-compose.dependencies.yml stop"
alias ddb="docker-compose -f docker-compose.dependencies.yml build"
alias ddr="docker-compose -f docker-compose.dependencies.yml run --rm"
alias dde="docker-compose -f docker-compose.dependencies.yml exec"
alias ddp="docker-compose -f docker-compose.dependencies.yml ps -a"
alias ddl="docker-compose -f docker-compose.dependencies.yml logs"
